### ISSUE TITLE
Проблемы при использовании шрифта

### ISSUE THREAD

**Issue by 10522** [DgINC/nineparchments-font#1]
Установил шрифты по вашему гайду, выглядит красиво, но есть 3 проблемы, которые желательно бы решить:

1. Не перерисованна заглавная буква "Д", она выглядит вот так: "D".
2. Не везде используется красивый шрифт. Например, в менюшках достижения, статистика, персонажи, используется старый шрифт, хотя в английском языке, шрифт там тоже красивый. Возможно, это из-за шрифта "nineparchments_wide".
3. В меню достижения некоторый текст вылазит за экран. Это происходит из-за того, что мы изменяем скрипт, т.е. выключаем совместимый шрифт для русского языка. Я довольно много экспериментировал (у меня гог версия, если что) со шрифтами и скриптом, но у меня не получилось поставить красивый шрифт без изменения скрипта.

Возможно, у вас получится решить данные проблемы. Если что, пишите, постараюсь ответить.

**Comment by DgINC** [comment]
1. Литера "Д" выглядит так потому что так она ближе всего похожа на оригинал. Есть смысл немного переделать её, но я подумаю над этим, но ничего не обещаю.
2-3. Без исходников игры я ничего сделать не могу, а декомпилить Lua нет желания, и вообще этот скрипт из Trine3 так что полная работоспособность не гарантируется. Единственный вариант просить финнов добавить шрифт в релиз стима, что крайне проблематично.
ps. Из-за первого вопроса пока не закрываю.

**Comment by 10522** [comment]
Скрипты вообще не нужно трогать, т.к. это приводит к проблемам, которые я описал выше. Можно узнать у разработчиков, какой шрифт используется при "_useCompatibilityFont = true_", а какой при "_useCompatibilityFont2 = true_". У русского языка эти параметры имеют значение "_true_". А в английском языке у этих параметров значение "_false_" и используется шрифт "nineparchments". Есть ещё шрифт "nineparchments_wide", возможно он и используется в тех менюшках, которые я указал выше.

Все шрифты содержащиеся в игре (но не все из них могут использоваться) находятся в папке: <папка с игрой>\data\gui\font

В Trine 2 и 3, если изменить шрифт в этой папке, то он меняется и в игре. Также можно установить шрифт в Windows, он тоже изменится в игре. Можете сами попробовать заменить только скрипт, а шрифт установить в Windows.

Вообщем, я не силён в редактировании шрифтов, но скорее всего, чтобы решить данные проблемы, нужно перерисовать остальные шрифты из этой папки и методом исключения найдутся шрифты, которые используются для русского языка. Если хотите, можете скинуть мне архив с перерисованными шрифтами и я сам протестирую их в игре.

**Comment by DgINC** [comment]
Как я сказал ранее, без исходников я ничего не могу сделать, а исходники нам никто не даст. В игре используется шрифт "nineparchments", "nineparchments_wide" используется для вывода изображений с нестандартной пропорцией. Остальные шрифты которые есть в архивах игры являються аппендиксом и в игре не используются.
Всё что есть находится в репозитарии, и больше нет ничего.
Ещё раз повторю, вы можете попросить финнов добавить шрифт в игру с правками для правильного отображения. Но как они написали, они не планируют обновлять игру, пот этому я думаю у вас вряд ли что-то получится.
upd. Написал финнам по пофоду этой проблемы, посмотрим что ответят.

**Comment by 10522** [comment]
Вы вообще ничего не поняли из того, что я написал. Если в игре используется только шрифт "nineparchments", то почему при его изменении, русские буквы в игре не меняются, а для этого нужно ещё и скрипт изменить?

А я вам отвечу, что для английского языка используется шрифт "nineparchments", а для русского совсем другой шрифт, т.к. если декомпилировать файл скрипта утилитой "unluac", то у русского языка параметры "_useCompatibilityFont_" и "_useCompatibilityFont2_" имеют значение "_true_", это означает, что для данного языка будет использоваться другой шрифт. В вашем же скрипте эти параметры имеют значение "_false_", это означает, что вы заставляете русский язык использовать шрифт "nineparchments", что и приводит к вышеописанным проблемам.

Я уже делал некоторые эксперименты со шрифтами, т.е. брал ваш шрифт и через утилиту "fontforge" изменял системную информацию шрифта, чтобы он был как другие шрифты из папки "font", но с вашими буквами. К сожалению, это не дало эффекта, возможно нужно делать по другому, поэтому я и написал вам последний абзац в предыдущем сообщении.

Кстати, я уже ранее изменял русский шрифт в Trine 2 и 3, т.к. он там тоже не очень красивый, в отличии от английского. Красивый русский шрифт я брал из русификатора к Trine 1. Самое главное было определить какой шрифт используется для английского, а какой для русского языка, это "Argos" и "Cambria" соответственно. Мне очень повезло, эту информацию я нашёл [тут](https://wiki.frozenbyte.com/index.php/Adding_a_new_language_as_a_MOD#Languages_and_font_issues) и мне не пришлось вручную выискивать шрифты. Затем, экспериментируя, я нашёл аж 4 способа изменить русский шрифт в игре, при этом ни один скрипт не пострадал. А с этой игрой ничего не получилось, потому что изначально изменяется не тот шрифт.

**Comment by 10522** [comment]
Вообщем, благодаря программе "FontCreator" удалось узнать, что английский язык использует шрифт "nineparchments", а русский язык шрифт "m_2c_regular".

То есть, вот что осталось сделать: перерисовать заглавную букву "Д", затем вместе с остальными буквами, добавить их в шрифт "m_2c_regular", затем установить этот шрифт в Windows, затем  убедиться, что в игре всё работает, затем обновить "README.md" и наконец, закрыть эту тему и спокойно играть в игру.

**Comment by 10522** [comment]
Исправленный шрифт к Nine Parchments есть в моём проекте: "[Русификаторы и красивые шрифты для всех игр от Frozenbyte](https://forum.zoneofgames.ru/topic/39690-rusifikatory-i-krasivye-shrifty-dlya-vseh-igr-ot-frozenbyte/)".
